name: PR Validation
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  contents: read # for checkout

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        with:
          preset: conventional-changelog-eslint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
